# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Testcreateteam' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testcreateteam' do
    @driver.get('http://localhost:3000/')
    @driver.manage.resize_to(882, 697)
    @driver.find_element(:css, '.button_to:nth-child(1) > .btn').click
    @driver.find_element(:id, 'user_email').send_keys('user5@user.ru')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, '.btn-close').click
    @driver.find_element(:link_text, 'Команда').click
    @driver.find_element(:id, 'user_first_name').click
    @driver.find_element(:id, 'user_first_name').send_keys('Михаил')
    @driver.find_element(:id, 'user_last_name').click
    @driver.find_element(:id, 'user_last_name').send_keys('Овакимян')
    @driver.find_element(:id, 'user_current_password').click
    @driver.find_element(:id, 'user_current_password').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, '.btn-close').click
    @driver.find_element(:link_text, 'Команда').click
    @driver.find_element(:id, 'teams_name').click
    @driver.find_element(:id, 'teams_name').send_keys('New sample team')
    dropdown = @driver.find_element(:id, 'teams_track')
    dropdown.find_element(:xpath, "//option[. = 'Java-backend']").click
    @driver.find_element(:css, 'option:nth-child(4)').click
    @driver.find_element(:css, '.actions:nth-child(4) .btn').click
    @driver.find_element(:link_text, 'BEAST Hack').click
    @driver.find_element(:link_text, 'Команда').click
    @driver.find_element(:css, '.btn-danger').click
    @driver.find_element(:link_text, 'Личный кабинет').click
    @driver.find_element(:id, 'user_first_name').click
    @driver.find_element(:id, 'user_first_name').click
    element = @driver.find_element(:id, 'user_first_name')
    @driver.action.double_click(element).perform
    @driver.find_element(:id, 'user_first_name').send_keys(' ')
    @driver.find_element(:id, 'user_last_name').click
    @driver.find_element(:id, 'user_last_name').click
    element = @driver.find_element(:id, 'user_last_name')
    @driver.action.double_click(element).perform
    @driver.find_element(:id, 'user_last_name').send_keys(' ')
    @driver.find_element(:id, 'user_current_password').click
    @driver.find_element(:id, 'user_current_password').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, '.btn-close').click
    @driver.find_element(:css, '.btn').click
    @driver.find_element(:css, '.btn-close').click
  end
end
