# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Testunauthenticatedrestrictions' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testunauthenticatedrestrictions' do
    @driver.get('http://localhost:3000/')
    @driver.manage.resize_to(882, 697)
    @driver.find_element(:link_text, 'О нас').click
    @driver.find_element(:link_text, 'Партнерам').click
    @driver.get('http://localhost:3000posts')
  end
end
